name: PHPCS

on:
  pull_request:
    branches:
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.0'

      - name: Install PHPCS
        run: |
          mkdir -p vendor/bin
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          chmod +x phpcs.phar
          mv phpcs.phar vendor/bin/phpcs

      - name: Run PHPCS for exit code
        id: phpcs-exit
        run: |
          vendor/bin/phpcs --standard=phpcs.xml.dist
          echo "PHPCS_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Generate PHPCS HTML Report
        run: |
          vendor/bin/phpcs --standard=phpcs.xml.dist --report=full --report-file=phpcs-report.html || true
          if [ "${{ env.PHPCS_EXIT_CODE }}" -eq 0 ]; then
            echo "<p style='color:green; font-weight:bold;'>Good job, you are able to merge this request!</p>" >> phpcs-report.html
          fi

      - name: Upload PHPCS HTML Artifact
        uses: actions/upload-artifact@v4
        with:
          name: phpcs-html-report
          path: phpcs-report.html

      - name: Fail if PHPCS has errors
        if: ${{ env.PHPCS_EXIT_CODE != 0 }}
        run: |
          echo "::error file=phpcs.xml.dist::PHPCS a găsit erori. Verificați raportul HTML!"
          exit 1
