name: PHPCS

on:
  pull_request:
    branches:
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.0'

      - name: Install PHPCS
        run: |
          mkdir -p vendor/bin
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          chmod +x phpcs.phar
          mv phpcs.phar vendor/bin/phpcs

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=phpcs.xml.dist --report=checkstyle | tee phpcs-report.xml

      - name: Run PHPCS
        id: phpcs
        run: |
          echo "RulÄƒm PHPCS conform phpcs.xml.dist..."
          vendor/bin/phpcs --standard=phpcs.xml.dist --report=checkstyle > phpcs-checkstyle.xml || true
          vendor/bin/phpcs --standard=phpcs.xml.dist
          # If there are some errors, return non 0 code
          PHPCS_EXIT_CODE=$(vendor/bin/phpcs --standard=phpcs.xml.dist --report=summary | tail -n1 | awk '{print $2}')
          if [ "$PHPCS_EXIT_CODE" -ne 0 ]; then
            echo "::error file=phpcs.xml.dist::PHPCS found some issues. Check the HTML Report for more info!"
            exit 1
          fi

      - name: Generate PHPCS HTML Report
        run: |
          vendor/bin/phpcs --standard=phpcs.xml.dist --report=full --report-file=phpcs-report.html || true
          PHPCS_EXIT_CODE=$(vendor/bin/phpcs --standard=phpcs.xml.dist --report=summary | tail -n1 | awk '{print $2}')
          if [ "$PHPCS_EXIT_CODE" -eq 0 ]; then
            echo "<p style='color:green; font-weight:bold;'>Good job, you are able to merge this request!</p>" >> phpcs-report.html
          fi

      - name: Upload PHPCS HTML Artifact
        uses: actions/upload-artifact@v4
        with:
          name: phpcs-html-report
          path: phpcs-report.html
