name: PHPCS

on:
  pull_request:
    branches:
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install PHPCS
        run: |
          mkdir -p vendor/bin
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          chmod +x phpcs.phar
          mv phpcs.phar vendor/bin/phpcs

      - name: Run PHPCS
        id: phpcs
        run: |
          vendor/bin/phpcs --standard=phpcs.xml.dist || true
          echo "PHPCS_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Generate PHPCS HTML Report
        run: |
          vendor/bin/phpcs --standard=phpcs.xml.dist --report=full --report-file=phpcs-report.html || true
          if [ "${{ env.PHPCS_EXIT_CODE }}" -eq 0 ]; then
            echo "<h2 style='color:green;'>Good job, you are able to merge this request!</h2>" >> phpcs-report.html
          fi

  deploy:
    needs: phpcs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  fail-if-errors:
    needs: phpcs
    runs-on: ubuntu-latest
    if: ${{ needs.phpcs.outputs.PHPCS_EXIT_CODE != 0 }}
    steps:
      - run: |
          echo "::error ::PHPCS a găsit erori. Verificați raportul HTML pe GitHub Pages!"
          exit 1
